#!/usr/bin/env node
function ba(){return function(a){return a}}function g(a){return function(){return this[a]}}function n(a){return function(){return a}}var r;
function s(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ca(a){return"string"==typeof a}var da="closure_uid_"+(1E9*Math.random()>>>0),ea=0;function fa(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};function ga(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("[goog.string.format] Template required");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,l,m,p,q){if("%"==m)return"%";var u=c.shift();if("undefined"==typeof u)throw Error("[goog.string.format] Not enough arguments");arguments[0]=u;return ga.ea[m].apply(null,arguments)})}ga.ea={};
ga.ea.s=function(a,b,c){return isNaN(c)||""==c||a.length>=c?a:a=-1<b.indexOf("-",0)?a+Array(c-a.length+1).join(" "):Array(c-a.length+1).join(" ")+a};
ga.ea.f=function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=a.toFixed(e));var f;f=0>a?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=a&&(d=f+d);if(isNaN(c)||d.length>=c)return d;d=isNaN(e)?Math.abs(a).toString():Math.abs(a).toFixed(e);a=c-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Array(a+1).join(" "):f+Array(a+1).join(0<=b.indexOf("0",0)?"0":" ")+d};ga.ea.d=function(a,b,c,d,e,f,h,k){return ga.ea.f(parseInt(a,10),b,c,d,0,f,h,k)};ga.ea.i=ga.ea.d;ga.ea.u=ga.ea.d;function ha(a,b){null!=a&&this.append.apply(this,arguments)}ha.prototype.ra="";ha.prototype.append=function(a,b,c){this.ra+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.ra+=arguments[d];return this};ha.prototype.toString=g("ra");function ia(){throw Error("No *print-fn* fn set for evaluation environment");}function ja(a){return ia=a}var ka=["cljs","core","set_print_fn_BANG_"],la=this;ka[0]in la||!la.execScript||la.execScript("var "+ka[0]);for(var ma;ka.length&&(ma=ka.shift());)ka.length||void 0===ja?la=la[ma]?la[ma]:la[ma]={}:la[ma]=ja;function oa(){var a=["\ufdd0:flush-on-newline",!0,"\ufdd0:readably",!0,"\ufdd0:meta",!1,"\ufdd0:dup",!1];return new pa(null,a.length/2,a,null)}function t(a){return null!=a&&!1!==a}
function qa(a){var b=ca(a);return b?"\ufdd0"!==a.charAt(0):b}function v(a,b){return a[s(null==b?null:b)]?!0:a._?!0:!1}var ra=null;function sa(a){return null==a?null:a.constructor}function w(a,b){var c=sa(b),c=t(t(c)?c.ib:c)?c.hb:s(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function ta(a){var b=a.hb;return t(b)?b:""+x(a)}var ua={},va={};
function y(a){if(a?a.I:a)return a.I(a);var b;b=y[s(null==a?null:a)];if(!b&&(b=y._,!b))throw w("ICounted.-count",a);return b.call(null,a)}function wa(a,b){if(a?a.C:a)return a.C(a,b);var c;c=wa[s(null==a?null:a)];if(!c&&(c=wa._,!c))throw w("ICollection.-conj",a);return c.call(null,a,b)}
var xa={},z=function(){function a(a,b,c){if(a?a.K:a)return a.K(a,b,c);var h;h=z[s(null==a?null:a)];if(!h&&(h=z._,!h))throw w("IIndexed.-nth",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.F:a)return a.F(a,b);var c;c=z[s(null==a?null:a)];if(!c&&(c=z._,!c))throw w("IIndexed.-nth",a);return c.call(null,a,b)}var c=null,c=function(d,c,f){switch(arguments.length){case 2:return b.call(this,d,c);case 3:return a.call(this,d,c,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}(),
ya={};function B(a){if(a?a.R:a)return a.R(a);var b;b=B[s(null==a?null:a)];if(!b&&(b=B._,!b))throw w("ISeq.-first",a);return b.call(null,a)}function D(a){if(a?a.S:a)return a.S(a);var b;b=D[s(null==a?null:a)];if(!b&&(b=D._,!b))throw w("ISeq.-rest",a);return b.call(null,a)}
var za={},Aa=function(){function a(a,b,c){if(a?a.L:a)return a.L(a,b,c);var h;h=Aa[s(null==a?null:a)];if(!h&&(h=Aa._,!h))throw w("ILookup.-lookup",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.U:a)return a.U(a,b);var c;c=Aa[s(null==a?null:a)];if(!c&&(c=Aa._,!c))throw w("ILookup.-lookup",a);return c.call(null,a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}();
function Ba(a,b,c){if(a?a.ca:a)return a.ca(a,b,c);var d;d=Ba[s(null==a?null:a)];if(!d&&(d=Ba._,!d))throw w("IAssociative.-assoc",a);return d.call(null,a,b,c)}var Ca={},Da={};function Ea(a){if(a?a.Xa:a)return a.Xa(a);var b;b=Ea[s(null==a?null:a)];if(!b&&(b=Ea._,!b))throw w("IMapEntry.-key",a);return b.call(null,a)}function Fa(a){if(a?a.Ya:a)return a.Ya(a);var b;b=Fa[s(null==a?null:a)];if(!b&&(b=Fa._,!b))throw w("IMapEntry.-val",a);return b.call(null,a)}var Ga={};
function Ha(a,b,c){if(a?a.Qa:a)return a.Qa(a,b,c);var d;d=Ha[s(null==a?null:a)];if(!d&&(d=Ha._,!d))throw w("IVector.-assoc-n",a);return d.call(null,a,b,c)}var Ia={};function Ja(a){if(a?a.N:a)return a.N(a);var b;b=Ja[s(null==a?null:a)];if(!b&&(b=Ja._,!b))throw w("IMeta.-meta",a);return b.call(null,a)}function Ka(a,b){if(a?a.Q:a)return a.Q(a,b);var c;c=Ka[s(null==a?null:a)];if(!c&&(c=Ka._,!c))throw w("IWithMeta.-with-meta",a);return c.call(null,a,b)}
var La={},Ma=function(){function a(a,b,c){if(a?a.P:a)return a.P(a,b,c);var h;h=Ma[s(null==a?null:a)];if(!h&&(h=Ma._,!h))throw w("IReduce.-reduce",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.O:a)return a.O(a,b);var c;c=Ma[s(null==a?null:a)];if(!c&&(c=Ma._,!c))throw w("IReduce.-reduce",a);return c.call(null,a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}();
function Na(a,b){if(a?a.A:a)return a.A(a,b);var c;c=Na[s(null==a?null:a)];if(!c&&(c=Na._,!c))throw w("IEquiv.-equiv",a);return c.call(null,a,b)}function Oa(a){if(a?a.D:a)return a.D(a);var b;b=Oa[s(null==a?null:a)];if(!b&&(b=Oa._,!b))throw w("IHash.-hash",a);return b.call(null,a)}function Pa(a){if(a?a.G:a)return a.G(a);var b;b=Pa[s(null==a?null:a)];if(!b&&(b=Pa._,!b))throw w("ISeqable.-seq",a);return b.call(null,a)}var Qa={};
function E(a,b){if(a?a.Za:a)return a.Za(0,b);var c;c=E[s(null==a?null:a)];if(!c&&(c=E._,!c))throw w("IWriter.-write",a);return c.call(null,a,b)}function Ra(a){if(a?a.gb:a)return null;var b;b=Ra[s(null==a?null:a)];if(!b&&(b=Ra._,!b))throw w("IWriter.-flush",a);return b.call(null,a)}var Sa={};function Ta(a,b,c){if(a?a.B:a)return a.B(a,b,c);var d;d=Ta[s(null==a?null:a)];if(!d&&(d=Ta._,!d))throw w("IPrintWithWriter.-pr-writer",a);return d.call(null,a,b,c)}
function Ua(a){if(a?a.xa:a)return a.xa(a);var b;b=Ua[s(null==a?null:a)];if(!b&&(b=Ua._,!b))throw w("IEditableCollection.-as-transient",a);return b.call(null,a)}function Va(a,b){if(a?a.ta:a)return a.ta(a,b);var c;c=Va[s(null==a?null:a)];if(!c&&(c=Va._,!c))throw w("ITransientCollection.-conj!",a);return c.call(null,a,b)}function Wa(a){if(a?a.ya:a)return a.ya(a);var b;b=Wa[s(null==a?null:a)];if(!b&&(b=Wa._,!b))throw w("ITransientCollection.-persistent!",a);return b.call(null,a)}
function Xa(a,b,c){if(a?a.oa:a)return a.oa(a,b,c);var d;d=Xa[s(null==a?null:a)];if(!d&&(d=Xa._,!d))throw w("ITransientAssociative.-assoc!",a);return d.call(null,a,b,c)}function Ya(a){if(a?a.Sa:a)return a.Sa();var b;b=Ya[s(null==a?null:a)];if(!b&&(b=Ya._,!b))throw w("IChunk.-drop-first",a);return b.call(null,a)}function Za(a){if(a?a.Ba:a)return a.Ba(a);var b;b=Za[s(null==a?null:a)];if(!b&&(b=Za._,!b))throw w("IChunkedSeq.-chunked-first",a);return b.call(null,a)}
function $a(a){if(a?a.wa:a)return a.wa(a);var b;b=$a[s(null==a?null:a)];if(!b&&(b=$a._,!b))throw w("IChunkedSeq.-chunked-rest",a);return b.call(null,a)}function ab(a){this.jb=a;this.q=0;this.h=1073741824}ab.prototype.Za=function(a,b){return this.jb.append(b)};ab.prototype.gb=n(null);function F(a){var b=new ha,c=new ab(b);a.B(a,c,oa());Ra(c);return""+x(b)}
function G(a){if(null==a)return null;var b;b=a?((b=a.h&8388608)?b:a.rb)?!0:!1:!1;if(b)return a.G(a);if(a instanceof Array||qa(a))return 0===a.length?null:new bb(a,0);if(v(za,a))return Pa(a);throw Error([x(a),x("is not ISeqable")].join(""));}function H(a){if(null==a)return null;var b;b=a?((b=a.h&64)?b:a.sa)?!0:!1:!1;if(b)return a.R(a);a=G(a);return null==a?null:B(a)}function J(a){if(null!=a){var b;b=a?((b=a.h&64)?b:a.sa)?!0:!1:!1;if(b)return a.S(a);a=G(a);return null!=a?D(a):L}return L}
function M(a){if(null==a)a=null;else{var b;b=a?((b=a.h&128)?b:a.qb)?!0:!1:!1;a=b?a.ha(a):G(J(a))}return a}
var cb=function(){function a(a,b){var c=a===b;return c?c:Na(a,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=N(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(t(b.b(a,d)))if(M(e))a=d,d=H(e),e=M(e);else return b.b(d,H(e));else return!1}a.r=2;a.m=function(a){var b=H(a);a=M(a);var d=H(a);a=J(a);return c(b,d,a)};a.k=c;return a}(),b=function(b,e,f){switch(arguments.length){case 1:return!0;case 2:return a.call(this,b,e);default:return c.k(b,
e,N(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.r=2;b.m=c.m;b.e=n(!0);b.b=a;b.k=c.k;return b}();Oa["null"]=n(0);va["null"]=!0;y["null"]=n(0);Na["null"]=function(a,b){return null==b};Ka["null"]=n(null);Ia["null"]=!0;Ja["null"]=n(null);Ca["null"]=!0;Date.prototype.A=function(a,b){var c=b instanceof Date;return c?a.toString()===b.toString():c};Oa.number=function(a){return Math.floor(a)%2147483647};Na.number=function(a,b){return a===b};Oa["boolean"]=function(a){return!0===a?1:0};
Ia["function"]=!0;Ja["function"]=n(null);ua["function"]=!0;Oa._=function(a){return a[da]||(a[da]=++ea)};
var db=function(){function a(a,b,c,d){for(var l=y(a);;)if(d<l)c=b.b?b.b(c,z.b(a,d)):b.call(null,c,z.b(a,d)),d+=1;else return c}function b(a,b,c){for(var d=y(a),l=0;;)if(l<d)c=b.b?b.b(c,z.b(a,l)):b.call(null,c,z.b(a,l)),l+=1;else return c}function c(a,b){var c=y(a);if(0===c)return b.la?"":b.call(null);for(var d=z.b(a,0),l=1;;)if(l<c)d=b.b?b.b(d,z.b(a,l)):b.call(null,d,z.b(a,l)),l+=1;else return d}var d=null,d=function(d,f,h,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,
d,f,h);case 4:return a.call(this,d,f,h,k)}throw Error("Invalid arity: "+arguments.length);};d.b=c;d.c=b;d.p=a;return d}(),eb=function(){function a(a,b,c,d){for(var l=a.length;;)if(d<l)c=b.b?b.b(c,a[d]):b.call(null,c,a[d]),d+=1;else return c}function b(a,b,c){for(var d=a.length,l=0;;)if(l<d)c=b.b?b.b(c,a[l]):b.call(null,c,a[l]),l+=1;else return c}function c(a,b){var c=a.length;if(0===a.length)return b.la?"":b.call(null);for(var d=a[0],l=1;;)if(l<c)d=b.b?b.b(d,a[l]):b.call(null,d,a[l]),l+=1;else return d}
var d=null,d=function(d,f,h,k){switch(arguments.length){case 2:return c.call(this,d,f);case 3:return b.call(this,d,f,h);case 4:return a.call(this,d,f,h,k)}throw Error("Invalid arity: "+arguments.length);};d.b=c;d.c=b;d.p=a;return d}();function fb(a){if(a){var b=a.h&2;a=(b?b:a.ab)?!0:a.h?!1:v(va,a)}else a=v(va,a);return a}function gb(a){if(a){var b=a.h&16;a=(b?b:a.Wa)?!0:a.h?!1:v(xa,a)}else a=v(xa,a);return a}function bb(a,b){this.a=a;this.j=b;this.q=0;this.h=166199550}r=bb.prototype;
r.D=function(a){return O.e?O.e(a):O.call(null,a)};r.ha=function(){return this.j+1<this.a.length?new bb(this.a,this.j+1):null};r.C=function(a,b){return P.b?P.b(b,a):P.call(null,b,a)};r.toString=function(){return F(this)};r.O=function(a,b){return eb.p(this.a,b,this.a[this.j],this.j+1)};r.P=function(a,b,c){return eb.p(this.a,b,c,this.j)};r.G=ba();r.I=function(){return this.a.length-this.j};r.R=function(){return this.a[this.j]};
r.S=function(){return this.j+1<this.a.length?new bb(this.a,this.j+1):hb.la?"":hb.call(null)};r.A=function(a,b){return Q.b?Q.b(a,b):Q.call(null,a,b)};r.F=function(a,b){var c=b+this.j;return c<this.a.length?this.a[c]:null};r.K=function(a,b,c){a=b+this.j;return a<this.a.length?this.a[a]:c};
var ib=function(){function a(a,b){return b<a.length?new bb(a,b):null}function b(a){return c.b(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.e=b;c.b=a;return c}(),N=function(){function a(a,b){return ib.b(a,b)}function b(a){return ib.b(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+
arguments.length);};c.e=b;c.b=a;return c}();La.array=!0;Ma.array=function(a,b){return eb.b(a,b)};Ma.array=function(a,b,c){return eb.c(a,b,c)};Na._=function(a,b){return a===b};
var jb=function(){function a(a,b){return null!=a?wa(a,b):hb.e?hb.e(b):hb.call(null,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=N(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(t(e))a=b.b(a,d),d=H(e),e=M(e);else return b.b(a,d)}a.r=2;a.m=function(a){var b=H(a);a=M(a);var d=H(a);a=J(a);return c(b,d,a)};a.k=c;return a}(),b=function(b,e,f){switch(arguments.length){case 2:return a.call(this,b,e);default:return c.k(b,
e,N(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.r=2;b.m=c.m;b.b=a;b.k=c.k;return b}();function R(a){if(null!=a){var b;b=a?((b=a.h&2)?b:a.ab)?!0:!1:!1;if(b)a=a.I(a);else if(a instanceof Array)a=a.length;else if(qa(a))a=a.length;else if(v(va,a))a=y(a);else a:{a=G(a);for(b=0;;){if(fb(a)){a=b+y(a);break a}a=M(a);b+=1}a=void 0}}else a=0;return a}
var kb=function(){function a(a,b,c){for(;;){if(null==a)return c;if(0===b)return G(a)?H(a):c;if(gb(a))return z.c(a,b,c);if(G(a))a=M(a),b-=1;else return c}}function b(a,b){for(;;){if(null==a)throw Error("Index out of bounds");if(0===b){if(G(a))return H(a);throw Error("Index out of bounds");}if(gb(a))return z.b(a,b);if(G(a)){var c=M(a),h=b-1;a=c;b=h}else throw Error("Index out of bounds");}}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,
c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}(),lb=function(){function a(a,b,c){if(null!=a){if(function(){var b;b=a?((b=a.h&16)?b:a.Wa)?!0:!1:!1;return b}())return a.K(a,Math.floor(b),c);if(a instanceof Array||qa(a))return b<a.length?a[b]:c;if(v(xa,a))return z.b(a,b);if(function(){var b;b=a?((b=a.h&64)?b:a.sa)?!0:a.h?!1:v(ya,a):v(ya,a);return b}())return kb.c(a,Math.floor(b),c);throw Error([x("nth not supported on this type "),x(ta(sa(a)))].join(""));}return c}function b(a,
b){if(null==a)return null;if(function(){var b;b=a?((b=a.h&16)?b:a.Wa)?!0:!1:!1;return b}())return a.F(a,Math.floor(b));if(a instanceof Array||qa(a))return b<a.length?a[b]:null;if(v(xa,a))return z.b(a,b);if(function(){var b;b=a?((b=a.h&64)?b:a.sa)?!0:a.h?!1:v(ya,a):v(ya,a);return b}())return kb.b(a,Math.floor(b));throw Error([x("nth not supported on this type "),x(ta(sa(a)))].join(""));}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,
e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}(),nb=function(){function a(a,b,c){if(null!=a){var h;h=a?((h=a.h&256)?h:a.Pa)?!0:!1:!1;a=h?a.L(a,b,c):a instanceof Array?b<a.length?a[b]:c:qa(a)?b<a.length?a[b]:c:v(za,a)?Aa.c(a,b,c):c}else a=c;return a}function b(a,b){var c;null==a?c=null:(c=a?((c=a.h&256)?c:a.Pa)?!0:!1:!1,c=c?a.U(a,b):a instanceof Array?b<a.length?a[b]:null:qa(a)?b<a.length?a[b]:null:v(za,a)?Aa.b(a,b):null);return c}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,
c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}(),pb=function(){function a(a,b,c){return null!=a?Ba(a,b,c):ob.b?ob.b(b,c):ob.call(null,b,c)}var b=null,c=function(){function a(b,d,k,l){var m=null;3<arguments.length&&(m=N(Array.prototype.slice.call(arguments,3),0));return c.call(this,b,d,k,m)}function c(a,d,e,l){for(;;)if(a=b.c(a,d,e),t(l))d=H(l),e=H(M(l)),l=M(M(l));else return a}a.r=3;a.m=function(a){var b=H(a);a=M(a);var d=H(a);a=M(a);
var l=H(a);a=J(a);return c(b,d,l,a)};a.k=c;return a}(),b=function(b,e,f,h){switch(arguments.length){case 3:return a.call(this,b,e,f);default:return c.k(b,e,f,N(arguments,3))}throw Error("Invalid arity: "+arguments.length);};b.r=3;b.m=c.m;b.c=a;b.k=c.k;return b}();function qb(a){var b="function"==s(a);return b?b:a?t(t(null)?null:a.mb)?!0:a.vb?!1:v(ua,a):v(ua,a)}function rb(a){var b;b=a?((b=a.h&131072)?b:a.cb)?!0:a.h?!1:v(Ia,a):v(Ia,a);return b?Ja(a):null}
var sb={},tb=0,S=function(){function a(a,b){var c=ca(a);(c?b:c)?(255<tb&&(sb={},tb=0),c=sb[a],"number"!==typeof c&&(c=fa(a),sb[a]=c,tb+=1)):c=Oa(a);return c}function b(a){return c.b(a,!0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.e=b;c.b=a;return c}();function ub(a){if(null==a)a=!1;else if(a){var b=a.h&1024;a=(b?b:a.pb)?!0:a.h?!1:v(Ca,a)}else a=v(Ca,a);return a}
function vb(a){if(a){var b=a.h&16384;a=(b?b:a.tb)?!0:a.h?!1:v(Ga,a)}else a=v(Ga,a);return a}function wb(a){if(a){var b=a.q&512;a=(b?b:a.nb)?!0:!1}else a=!1;return a}function xb(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,e-=1,b+=1}function yb(a){return t(a)?!0:!1}function zb(a){var b=ca(a);return b?"\ufdd0"===a.charAt(0):b}
function Ab(a,b){if(a===b)return 0;if(null==a)return-1;if(null==b)return 1;if(sa(a)===sa(b)){var c;c=a?((c=a.q&2048)?c:a.Ua)?!0:!1:!1;return c?a.Va(a,b):a>b?1:a<b?-1:0}throw Error("compare on non-nil objects of different types");}
var Bb=function(){function a(a,b,c,h){for(;;){var k=Ab(lb.b(a,h),lb.b(b,h)),l=0===k;if(l?h+1<c:l)h+=1;else return k}}function b(a,b){var f=R(a),h=R(b);return f<h?-1:f>h?1:c.p(a,b,f,0)}var c=null,c=function(c,e,f,h){switch(arguments.length){case 2:return b.call(this,c,e);case 4:return a.call(this,c,e,f,h)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.p=a;return c}(),U=function(){function a(a,b,c){for(c=G(c);;)if(c)b=a.b?a.b(b,H(c)):a.call(null,b,H(c)),c=M(c);else return b}function b(a,
b){var c=G(b);return c?Cb.c?Cb.c(a,H(c),M(c)):Cb.call(null,a,H(c),M(c)):a.la?"":a.call(null)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}(),Cb=function(){function a(a,b,c){var h;h=c?((h=c.h&524288)?h:c.fb)?!0:!1:!1;return h?c.P(c,a,b):c instanceof Array?eb.c(c,a,b):qa(c)?eb.c(c,a,b):v(La,c)?Ma.c(c,a,b):U.c(a,b,c)}function b(a,b){var c;c=b?((c=b.h&524288)?
c:b.fb)?!0:!1:!1;return c?b.O(b,a):b instanceof Array?eb.b(b,a):qa(b)?eb.b(b,a):v(La,b)?Ma.b(b,a):U.b(a,b)}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}();function Db(a){return 0<=a?Math.floor.e?Math.floor.e(a):Math.floor.call(null,a):Math.ceil.e?Math.ceil.e(a):Math.ceil.call(null,a)}
function Eb(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}
var Fb=function(){function a(a){return null==a?"":a.toString()}var b=null,c=function(){function a(b,d){var k=null;1<arguments.length&&(k=N(Array.prototype.slice.call(arguments,1),0));return c.call(this,b,k)}function c(a,d){return function(a,c){for(;;)if(t(c)){var d=a.append(b.e(H(c))),e=M(c);a=d;c=e}else return b.e(a)}.call(null,new ha(b.e(a)),d)}a.r=1;a.m=function(a){var b=H(a);a=J(a);return c(b,a)};a.k=c;return a}(),b=function(b,e){switch(arguments.length){case 0:return"";case 1:return a.call(this,
b);default:return c.k(b,N(arguments,1))}throw Error("Invalid arity: "+arguments.length);};b.r=1;b.m=c.m;b.la=n("");b.e=a;b.k=c.k;return b}(),x=function(){function a(a){return zb(a)?Fb.k(":",N([a.substring(2,a.length)],0)):null==a?"":a.toString()}var b=null,c=function(){function a(b,d){var k=null;1<arguments.length&&(k=N(Array.prototype.slice.call(arguments,1),0));return c.call(this,b,k)}function c(a,d){return function(a,c){for(;;)if(t(c)){var d=a.append(b.e(H(c))),e=M(c);a=d;c=e}else return Fb.e(a)}.call(null,
new ha(b.e(a)),d)}a.r=1;a.m=function(a){var b=H(a);a=J(a);return c(b,a)};a.k=c;return a}(),b=function(b,e){switch(arguments.length){case 0:return"";case 1:return a.call(this,b);default:return c.k(b,N(arguments,1))}throw Error("Invalid arity: "+arguments.length);};b.r=1;b.m=c.m;b.la=n("");b.e=a;b.k=c.k;return b}(),Gb=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return a.substring(c);case 3:return a.substring(c,d)}throw Error("Invalid arity: "+arguments.length);};a.b=function(a,
c){return a.substring(c)};a.c=function(a,c,d){return a.substring(c,d)};return a}();function Q(a,b){var c;c=b?((c=b.h&16777216)?c:b.sb)?!0:b.h?!1:v(Qa,b):v(Qa,b);if(c)a:{c=G(a);for(var d=G(b);;){if(null==c){c=null==d;break a}if(null!=d&&cb.b(H(c),H(d)))c=M(c),d=M(d);else{c=!1;break a}}c=void 0}else c=null;return yb(c)}function Hb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function O(a){return Cb.c(function(a,c){return Hb(a,S.b(c,!1))},S.b(H(a),!1),M(a))}
function Ib(a){var b=0;for(a=G(a);;)if(a){var c=H(a),b=(b+(S.e(V.e?V.e(c):V.call(null,c))^S.e(W.e?W.e(c):W.call(null,c))))%4503599627370496;a=M(a)}else return b}function Jb(a,b,c,d,e){this.n=a;this.ua=b;this.ga=c;this.count=d;this.l=e;this.q=0;this.h=65937646}r=Jb.prototype;r.D=function(a){var b=this.l;return null!=b?b:this.l=a=O(a)};r.ha=function(){return 1===this.count?null:this.ga};r.C=function(a,b){return new Jb(this.n,b,a,this.count+1,null)};r.toString=function(){return F(this)};
r.O=function(a,b){return U.b(b,a)};r.P=function(a,b,c){return U.c(b,c,a)};r.G=ba();r.I=g("count");r.R=g("ua");r.S=function(){return 1===this.count?L:this.ga};r.A=function(a,b){return Q(a,b)};r.Q=function(a,b){return new Jb(b,this.ua,this.ga,this.count,this.l)};r.N=g("n");function Kb(a){this.n=a;this.q=0;this.h=65937614}r=Kb.prototype;r.D=n(0);r.ha=n(null);r.C=function(a,b){return new Jb(this.n,b,null,1,null)};r.toString=function(){return F(this)};r.O=function(a,b){return U.b(b,a)};
r.P=function(a,b,c){return U.c(b,c,a)};r.G=n(null);r.I=n(0);r.R=n(null);r.S=function(){return L};r.A=function(a,b){return Q(a,b)};r.Q=function(a,b){return new Kb(b)};r.N=g("n");
var L=new Kb(null),hb=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b;if(a instanceof bb)b=a.a;else a:{for(b=[];;)if(null!=a)b.push(a.R(a)),a=a.ha(a);else break a;b=void 0}a=b.length;for(var e=L;;)if(0<a){var f=a-1,e=e.C(e,b[a-1]);a=f}else return e}a.r=0;a.m=function(a){a=G(a);return b(a)};a.k=b;return a}();function Lb(a,b,c,d){this.n=a;this.ua=b;this.ga=c;this.l=d;this.q=0;this.h=65929452}r=Lb.prototype;
r.D=function(a){var b=this.l;return null!=b?b:this.l=a=O(a)};r.ha=function(){return null==this.ga?null:Pa(this.ga)};r.C=function(a,b){return new Lb(null,b,a,this.l)};r.toString=function(){return F(this)};r.O=function(a,b){return U.b(b,a)};r.P=function(a,b,c){return U.c(b,c,a)};r.G=ba();r.R=g("ua");r.S=function(){return null==this.ga?L:this.ga};r.A=function(a,b){return Q(a,b)};r.Q=function(a,b){return new Lb(b,this.ua,this.ga,this.l)};r.N=g("n");
function P(a,b){var c=null==b;c||(c=b?((c=b.h&64)?c:b.sa)?!0:!1:!1);return c?new Lb(null,a,b,null):new Lb(null,a,G(b),null)}Oa.string=function(a){return fa(a)};function Mb(a){this.$a=a;this.q=0;this.h=1}
Mb.prototype.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:var e=a,e=this;if(null==c)e=null;else{var f;f=c?((f=c.h&256)?f:c.Pa)?!0:c.h?!1:v(za,c):v(za,c);e=f?Aa.c(c,e.$a,null):null}return e;case 3:return e=a,e=this,null==c?e=d:(f=c?((f=c.h&256)?f:c.Pa)?!0:c.h?!1:v(za,c):v(za,c),e=f?Aa.c(c,e.$a,d):null),e}throw Error("Invalid arity: "+arguments.length);}}();Mb.prototype.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};
String.prototype.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return nb.b(c,this.toString());case 3:return nb.c(c,this.toString(),d)}throw Error("Invalid arity: "+arguments.length);}}();String.prototype.apply=function(a,b){return a.call.apply(a,[a].concat(b.slice()))};String.prototype.apply=function(a,b){return 2>b.length?nb.b(b[0],a):nb.c(b[0],a,b[1])};function Nb(a){var b=a.x;if(a.Ra)return b;a.x=b.la?"":b.call(null);a.Ra=!0;return a.x}
function Ob(a,b,c,d){this.n=a;this.Ra=b;this.x=c;this.l=d;this.q=0;this.h=32374988}r=Ob.prototype;r.D=function(a){var b=this.l;return null!=b?b:this.l=a=O(a)};r.ha=function(a){return Pa(a.S(a))};r.C=function(a,b){return P(b,a)};r.toString=function(){return F(this)};r.O=function(a,b){return U.b(b,a)};r.P=function(a,b,c){return U.c(b,c,a)};r.G=function(a){return G(Nb(a))};r.R=function(a){return H(Nb(a))};r.S=function(a){return J(Nb(a))};r.A=function(a,b){return Q(a,b)};
r.Q=function(a,b){return new Ob(b,this.Ra,this.x,this.l)};r.N=g("n");function Pb(a,b){this.Aa=a;this.end=b;this.q=0;this.h=2}Pb.prototype.I=g("end");Pb.prototype.add=function(a){this.Aa[this.end]=a;return this.end+=1};Pb.prototype.ka=function(){var a=new Qb(this.Aa,0,this.end);this.Aa=null;return a};function Qb(a,b,c){this.a=a;this.t=b;this.end=c;this.q=0;this.h=524306}r=Qb.prototype;r.O=function(a,b){return eb.p(this.a,b,this.a[this.t],this.t+1)};r.P=function(a,b,c){return eb.p(this.a,b,c,this.t)};
r.Sa=function(){if(this.t===this.end)throw Error("-drop-first of empty chunk");return new Qb(this.a,this.t+1,this.end)};r.F=function(a,b){return this.a[this.t+b]};r.K=function(a,b,c){return((a=0<=b)?b<this.end-this.t:a)?this.a[this.t+b]:c};r.I=function(){return this.end-this.t};
var Rb=function(){function a(a,b,c){return new Qb(a,b,c)}function b(a,b){return new Qb(a,b,a.length)}function c(a){return new Qb(a,0,a.length)}var d=null,d=function(d,f,h){switch(arguments.length){case 1:return c.call(this,d);case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,h)}throw Error("Invalid arity: "+arguments.length);};d.e=c;d.b=b;d.c=a;return d}();function Sb(a,b,c,d){this.ka=a;this.ja=b;this.n=c;this.l=d;this.h=31850604;this.q=1536}r=Sb.prototype;
r.D=function(a){var b=this.l;return null!=b?b:this.l=a=O(a)};r.C=function(a,b){return P(b,a)};r.toString=function(){return F(this)};r.G=ba();r.R=function(){return z.b(this.ka,0)};r.S=function(){return 1<y(this.ka)?new Sb(Ya(this.ka),this.ja,this.n,null):null==this.ja?L:this.ja};r.Ta=function(){return null==this.ja?null:this.ja};r.A=function(a,b){return Q(a,b)};r.Q=function(a,b){return new Sb(this.ka,this.ja,b,this.l)};r.N=g("n");r.Ba=g("ka");r.wa=function(){return null==this.ja?L:this.ja};
function Tb(a){for(var b=[];;)if(G(a))b.push(H(a)),a=M(a);else return b}function Ub(a,b){if(fb(a))return R(a);for(var c=a,d=b,e=0;;){var f;f=(f=0<d)?G(c):f;if(t(f))c=M(c),d-=1,e+=1;else return e}}
var Xb=function Vb(b){return null==b?null:null==M(b)?G(H(b)):P(H(b),Vb(M(b)))},Yb=function(){function a(a,b,c,d){return P(a,P(b,P(c,d)))}function b(a,b,c){return P(a,P(b,c))}var c=null,d=function(){function a(c,d,e,m,p){var q=null;4<arguments.length&&(q=N(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,m,q)}function b(a,c,d,e,f){return P(a,P(c,P(d,P(e,Xb(f)))))}a.r=4;a.m=function(a){var c=H(a);a=M(a);var d=H(a);a=M(a);var e=H(a);a=M(a);var p=H(a);a=J(a);return b(c,d,e,p,a)};a.k=
b;return a}(),c=function(c,f,h,k,l){switch(arguments.length){case 1:return G(c);case 2:return P(c,f);case 3:return b.call(this,c,f,h);case 4:return a.call(this,c,f,h,k);default:return d.k(c,f,h,k,N(arguments,4))}throw Error("Invalid arity: "+arguments.length);};c.r=4;c.m=d.m;c.e=function(a){return G(a)};c.b=function(a,b){return P(a,b)};c.c=b;c.p=a;c.k=d.k;return c}();
function Zb(a,b,c){var d=G(c);if(0===b)return a.la?"":a.call(null);c=B(d);var e=D(d);if(1===b)return a.e?a.e(c):a.e?a.e(c):a.call(null,c);var d=B(e),f=D(e);if(2===b)return a.b?a.b(c,d):a.b?a.b(c,d):a.call(null,c,d);var e=B(f),h=D(f);if(3===b)return a.c?a.c(c,d,e):a.c?a.c(c,d,e):a.call(null,c,d,e);var f=B(h),k=D(h);if(4===b)return a.p?a.p(c,d,e,f):a.p?a.p(c,d,e,f):a.call(null,c,d,e,f);h=B(k);k=D(k);if(5===b)return a.J?a.J(c,d,e,f,h):a.J?a.J(c,d,e,f,h):a.call(null,c,d,e,f,h);a=B(k);var l=D(k);if(6===
b)return a.da?a.da(c,d,e,f,h,a):a.da?a.da(c,d,e,f,h,a):a.call(null,c,d,e,f,h,a);var k=B(l),m=D(l);if(7===b)return a.na?a.na(c,d,e,f,h,a,k):a.na?a.na(c,d,e,f,h,a,k):a.call(null,c,d,e,f,h,a,k);var l=B(m),p=D(m);if(8===b)return a.Na?a.Na(c,d,e,f,h,a,k,l):a.Na?a.Na(c,d,e,f,h,a,k,l):a.call(null,c,d,e,f,h,a,k,l);var m=B(p),q=D(p);if(9===b)return a.Oa?a.Oa(c,d,e,f,h,a,k,l,m):a.Oa?a.Oa(c,d,e,f,h,a,k,l,m):a.call(null,c,d,e,f,h,a,k,l,m);var p=B(q),u=D(q);if(10===b)return a.Ca?a.Ca(c,d,e,f,h,a,k,l,m,p):a.Ca?
a.Ca(c,d,e,f,h,a,k,l,m,p):a.call(null,c,d,e,f,h,a,k,l,m,p);var q=B(u),A=D(u);if(11===b)return a.Da?a.Da(c,d,e,f,h,a,k,l,m,p,q):a.Da?a.Da(c,d,e,f,h,a,k,l,m,p,q):a.call(null,c,d,e,f,h,a,k,l,m,p,q);var u=B(A),C=D(A);if(12===b)return a.Ea?a.Ea(c,d,e,f,h,a,k,l,m,p,q,u):a.Ea?a.Ea(c,d,e,f,h,a,k,l,m,p,q,u):a.call(null,c,d,e,f,h,a,k,l,m,p,q,u);var A=B(C),I=D(C);if(13===b)return a.Fa?a.Fa(c,d,e,f,h,a,k,l,m,p,q,u,A):a.Fa?a.Fa(c,d,e,f,h,a,k,l,m,p,q,u,A):a.call(null,c,d,e,f,h,a,k,l,m,p,q,u,A);var C=B(I),K=D(I);
if(14===b)return a.Ga?a.Ga(c,d,e,f,h,a,k,l,m,p,q,u,A,C):a.Ga?a.Ga(c,d,e,f,h,a,k,l,m,p,q,u,A,C):a.call(null,c,d,e,f,h,a,k,l,m,p,q,u,A,C);var I=B(K),T=D(K);if(15===b)return a.Ha?a.Ha(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I):a.Ha?a.Ha(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I):a.call(null,c,d,e,f,h,a,k,l,m,p,q,u,A,C,I);var K=B(T),aa=D(T);if(16===b)return a.Ia?a.Ia(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K):a.Ia?a.Ia(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K):a.call(null,c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K);var T=B(aa),na=D(aa);if(17===b)return a.Ja?
a.Ja(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T):a.Ja?a.Ja(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T):a.call(null,c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T);var aa=B(na),mb=D(na);if(18===b)return a.Ka?a.Ka(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T,aa):a.Ka?a.Ka(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T,aa):a.call(null,c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T,aa);na=B(mb);mb=D(mb);if(19===b)return a.La?a.La(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T,aa,na):a.La?a.La(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T,aa,na):a.call(null,c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T,aa,
na);var Wb=B(mb);D(mb);if(20===b)return a.Ma?a.Ma(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T,aa,na,Wb):a.Ma?a.Ma(c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T,aa,na,Wb):a.call(null,c,d,e,f,h,a,k,l,m,p,q,u,A,C,I,K,T,aa,na,Wb);throw Error("Only up to 20 arguments supported on functions");}
var $b=function(){function a(a,b,c,d,e){b=Yb.p(b,c,d,e);c=a.r;return a.m?(d=Ub(b,c+1),d<=c?Zb(a,d,b):a.m(b)):a.apply(a,Tb(b))}function b(a,b,c,d){b=Yb.c(b,c,d);c=a.r;return a.m?(d=Ub(b,c+1),d<=c?Zb(a,d,b):a.m(b)):a.apply(a,Tb(b))}function c(a,b,c){b=Yb.b(b,c);c=a.r;if(a.m){var d=Ub(b,c+1);return d<=c?Zb(a,d,b):a.m(b)}return a.apply(a,Tb(b))}function d(a,b){var c=a.r;if(a.m){var d=Ub(b,c+1);return d<=c?Zb(a,d,b):a.m(b)}return a.apply(a,Tb(b))}var e=null,f=function(){function a(c,d,e,f,h,A){var C=null;
5<arguments.length&&(C=N(Array.prototype.slice.call(arguments,5),0));return b.call(this,c,d,e,f,h,C)}function b(a,c,d,e,f,h){c=P(c,P(d,P(e,P(f,Xb(h)))));d=a.r;return a.m?(e=Ub(c,d+1),e<=d?Zb(a,e,c):a.m(c)):a.apply(a,Tb(c))}a.r=5;a.m=function(a){var c=H(a);a=M(a);var d=H(a);a=M(a);var e=H(a);a=M(a);var f=H(a);a=M(a);var h=H(a);a=J(a);return b(c,d,e,f,h,a)};a.k=b;return a}(),e=function(e,k,l,m,p,q){switch(arguments.length){case 2:return d.call(this,e,k);case 3:return c.call(this,e,k,l);case 4:return b.call(this,
e,k,l,m);case 5:return a.call(this,e,k,l,m,p);default:return f.k(e,k,l,m,p,N(arguments,5))}throw Error("Invalid arity: "+arguments.length);};e.r=5;e.m=f.m;e.b=d;e.c=c;e.p=b;e.J=a;e.k=f.k;return e}();function ac(a,b){for(;;){if(null==G(b))return!0;if(t(a.e?a.e(H(b)):a.call(null,H(b)))){var c=a,d=M(b);a=c;b=d}else return!1}}function bc(a){return a}
var cc=function(){function a(a,b,c,e){return new Ob(null,!1,function(){var m=G(b),p=G(c),q=G(e);return(m?p?q:p:m)?P(a.c?a.c(H(m),H(p),H(q)):a.call(null,H(m),H(p),H(q)),d.p(a,J(m),J(p),J(q))):null},null)}function b(a,b,c){return new Ob(null,!1,function(){var e=G(b),m=G(c);return(e?m:e)?P(a.b?a.b(H(e),H(m)):a.call(null,H(e),H(m)),d.c(a,J(e),J(m))):null},null)}function c(a,b){return new Ob(null,!1,function(){var c=G(b);if(c){if(wb(c)){for(var e=Za(c),m=R(e),p=new Pb(Array(m),0),q=0;;)if(q<m){var u=a.e?
a.e(z.b(e,q)):a.call(null,z.b(e,q));p.add(u);q+=1}else break;e=p.ka();c=d.b(a,$a(c));return 0===y(e)?c:new Sb(e,c,null,null)}return P(a.e?a.e(H(c)):a.call(null,H(c)),d.b(a,J(c)))}return null},null)}var d=null,e=function(){function a(c,d,e,f,q){var u=null;4<arguments.length&&(u=N(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,f,u)}function b(a,c,e,f,h){return d.b(function(b){return $b.b(a,b)},function A(a){return new Ob(null,!1,function(){var b=d.b(G,a);return ac(bc,b)?P(d.b(H,
b),A(d.b(J,b))):null},null)}(jb.k(h,f,N([e,c],0))))}a.r=4;a.m=function(a){var c=H(a);a=M(a);var d=H(a);a=M(a);var e=H(a);a=M(a);var f=H(a);a=J(a);return b(c,d,e,f,a)};a.k=b;return a}(),d=function(d,h,k,l,m){switch(arguments.length){case 2:return c.call(this,d,h);case 3:return b.call(this,d,h,k);case 4:return a.call(this,d,h,k,l);default:return e.k(d,h,k,l,N(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.r=4;d.m=e.m;d.b=c;d.c=b;d.p=a;d.k=e.k;return d}();
function dc(a,b){this.o=a;this.a=b}function ec(a){a=a.g;return 32>a?0:a-1>>>5<<5}function fc(a,b,c){for(;;){if(0===b)return c;var d=new dc(a,Array(32));d.a[0]=c;c=d;b-=5}}var hc=function gc(b,c,d,e){var f=new dc(d.o,d.a.slice()),h=b.g-1>>>c&31;5===c?f.a[h]=e:(d=d.a[h],b=null!=d?gc(b,c-5,d,e):fc(null,c-5,e),f.a[h]=b);return f};function ic(a,b){throw Error([x("No item "),x(a),x(" in vector of length "),x(b)].join(""));}
function jc(a,b){var c=0<=b;if(c?b<a.g:c){if(b>=ec(a))return a.H;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.a[b>>>d&31],d=e;else return c.a}else return ic(b,a.g)}var lc=function kc(b,c,d,e,f){var h=new dc(d.o,d.a.slice());if(0===c)h.a[e&31]=f;else{var k=e>>>c&31;b=kc(b,c-5,d.a[k],e,f);h.a[k]=b}return h};function X(a,b,c,d,e,f){this.n=a;this.g=b;this.shift=c;this.root=d;this.H=e;this.l=f;this.q=4;this.h=167668511}r=X.prototype;
r.xa=function(){return new mc(this.g,this.shift,nc.e?nc.e(this.root):nc.call(null,this.root),oc.e?oc.e(this.H):oc.call(null,this.H))};r.D=function(a){var b=this.l;return null!=b?b:this.l=a=O(a)};r.U=function(a,b){return a.K(a,b,null)};r.L=function(a,b,c){return a.K(a,b,c)};
r.ca=function(a,b,c){var d=0<=b;if(d?b<this.g:d)return ec(a)<=b?(a=this.H.slice(),a[b&31]=c,new X(this.n,this.g,this.shift,this.root,a,null)):new X(this.n,this.g,this.shift,lc(a,this.shift,this.root,b,c),this.H,null);if(b===this.g)return a.C(a,c);throw Error([x("Index "),x(b),x(" out of bounds  [0,"),x(this.g),x("]")].join(""));};
r.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.F(this,c);case 3:return this.K(this,c,d)}throw Error("Invalid arity: "+arguments.length);}}();r.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};
r.C=function(a,b){if(32>this.g-ec(a)){var c=this.H.slice();c.push(b);return new X(this.n,this.g+1,this.shift,this.root,c,null)}var d=this.g>>>5>1<<this.shift,c=d?this.shift+5:this.shift;if(d){d=new dc(null,Array(32));d.a[0]=this.root;var e=fc(null,this.shift,new dc(null,this.H));d.a[1]=e}else d=hc(a,this.shift,this.root,new dc(null,this.H));return new X(this.n,this.g+1,c,d,[b],null)};r.Xa=function(a){return a.F(a,0)};r.Ya=function(a){return a.F(a,1)};r.toString=function(){return F(this)};
r.O=function(a,b){return db.b(a,b)};r.P=function(a,b,c){return db.c(a,b,c)};r.G=function(a){return 0===this.g?null:32>this.g?N.e(this.H):Y.c?Y.c(a,0,0):Y.call(null,a,0,0)};r.I=g("g");r.Qa=function(a,b,c){return a.ca(a,b,c)};r.A=function(a,b){return Q(a,b)};r.Q=function(a,b){return new X(b,this.g,this.shift,this.root,this.H,this.l)};r.N=g("n");r.F=function(a,b){return jc(a,b)[b&31]};r.K=function(a,b,c){var d=0<=b;return(d?b<this.g:d)?a.F(a,b):c};var pc=new dc(null,Array(32));
function qc(a){var b=a.length;if(32>b)return new X(null,b,5,pc,a,null);for(var c=a.slice(0,32),d=32,e=Ua(new X(null,32,5,pc,c,null));;)if(d<b)c=d+1,e=Va(e,a[d]),d=c;else return Wa(e)}function rc(a,b,c,d,e,f){this.w=a;this.W=b;this.j=c;this.t=d;this.n=e;this.l=f;this.h=32243948;this.q=1536}r=rc.prototype;r.D=function(a){var b=this.l;return null!=b?b:this.l=a=O(a)};
r.ha=function(a){return this.t+1<this.W.length?(a=Y.p?Y.p(this.w,this.W,this.j,this.t+1):Y.call(null,this.w,this.W,this.j,this.t+1),null==a?null:a):a.Ta(a)};r.C=function(a,b){return P(b,a)};r.toString=function(){return F(this)};r.O=function(a,b){return db.b(sc.c?sc.c(this.w,this.j+this.t,R(this.w)):sc.call(null,this.w,this.j+this.t,R(this.w)),b)};r.P=function(a,b,c){return db.c(sc.c?sc.c(this.w,this.j+this.t,R(this.w)):sc.call(null,this.w,this.j+this.t,R(this.w)),b,c)};r.G=ba();r.R=function(){return this.W[this.t]};
r.S=function(a){return this.t+1<this.W.length?(a=Y.p?Y.p(this.w,this.W,this.j,this.t+1):Y.call(null,this.w,this.W,this.j,this.t+1),null==a?L:a):a.wa(a)};r.Ta=function(){var a=this.W.length,a=this.j+a<y(this.w)?Y.c?Y.c(this.w,this.j+a,0):Y.call(null,this.w,this.j+a,0):null;return null==a?null:a};r.A=function(a,b){return Q(a,b)};r.Q=function(a,b){return Y.J?Y.J(this.w,this.W,this.j,this.t,b):Y.call(null,this.w,this.W,this.j,this.t,b)};r.Ba=function(){return Rb.b(this.W,this.t)};
r.wa=function(){var a=this.W.length,a=this.j+a<y(this.w)?Y.c?Y.c(this.w,this.j+a,0):Y.call(null,this.w,this.j+a,0):null;return null==a?L:a};
var Y=function(){function a(a,b,c,d,l){return new rc(a,b,c,d,l,null)}function b(a,b,c,d){return new rc(a,b,c,d,null,null)}function c(a,b,c){return new rc(a,jc(a,b),b,c,null,null)}var d=null,d=function(d,f,h,k,l){switch(arguments.length){case 3:return c.call(this,d,f,h);case 4:return b.call(this,d,f,h,k);case 5:return a.call(this,d,f,h,k,l)}throw Error("Invalid arity: "+arguments.length);};d.c=c;d.p=b;d.J=a;return d}();
function tc(a,b,c,d,e){this.n=a;this.aa=b;this.start=c;this.end=d;this.l=e;this.q=0;this.h=32400159}r=tc.prototype;r.D=function(a){var b=this.l;return null!=b?b:this.l=a=O(a)};r.U=function(a,b){return a.K(a,b,null)};r.L=function(a,b,c){return a.K(a,b,c)};r.ca=function(a,b,c){var d=this,e=d.start+b;return uc.J?uc.J(d.n,pb.c(d.aa,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null):uc.call(null,d.n,pb.c(d.aa,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null)};
r.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.F(this,c);case 3:return this.K(this,c,d)}throw Error("Invalid arity: "+arguments.length);}}();r.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};r.C=function(a,b){return uc.J?uc.J(this.n,Ha(this.aa,this.end,b),this.start,this.end+1,null):uc.call(null,this.n,Ha(this.aa,this.end,b),this.start,this.end+1,null)};r.toString=function(){return F(this)};
r.O=function(a,b){return db.b(a,b)};r.P=function(a,b,c){return db.c(a,b,c)};r.G=function(){var a=this;return function c(d){return d===a.end?null:P(z.b(a.aa,d),new Ob(null,!1,function(){return c(d+1)},null))}(a.start)};r.I=function(){return this.end-this.start};r.Qa=function(a,b,c){return a.ca(a,b,c)};r.A=function(a,b){return Q(a,b)};r.Q=function(a,b){return uc.J?uc.J(b,this.aa,this.start,this.end,this.l):uc.call(null,b,this.aa,this.start,this.end,this.l)};r.N=g("n");
r.F=function(a,b){var c=0>b;return(c?c:this.end<=this.start+b)?ic(b,this.end-this.start):z.b(this.aa,this.start+b)};r.K=function(a,b,c){return((a=0>b)?a:this.end<=this.start+b)?c:z.c(this.aa,this.start+b,c)};function uc(a,b,c,d,e){for(;;)if(b instanceof tc){var f=b.start+c,h=b.start+d;b=b.aa;c=f;d=h}else{var k=R(b);if(function(){var a=0>c;return a||(a=0>d)?a:(a=c>k)?a:d>k}())throw Error("Index out of bounds");return new tc(a,b,c,d,e)}}
var sc=function(){function a(a,b,c){return uc(null,a,b,c,null)}function b(a,b){return c.c(a,b,R(a))}var c=null,c=function(c,e,f){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.b=b;c.c=a;return c}();function nc(a){return new dc({},a.a.slice())}function oc(a){var b=Array(32);xb(a,0,b,0,a.length);return b}
var wc=function vc(b,c,d,e){d=b.root.o===d.o?d:new dc(b.root.o,d.a.slice());var f=b.g-1>>>c&31;if(5===c)b=e;else{var h=d.a[f];b=null!=h?vc(b,c-5,h,e):fc(b.root.o,c-5,e)}d.a[f]=b;return d};function mc(a,b,c,d){this.g=a;this.shift=b;this.root=c;this.H=d;this.h=275;this.q=88}r=mc.prototype;r.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.U(this,c);case 3:return this.L(this,c,d)}throw Error("Invalid arity: "+arguments.length);}}();
r.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};r.U=function(a,b){return a.K(a,b,null)};r.L=function(a,b,c){return a.K(a,b,c)};r.F=function(a,b){if(this.root.o)return jc(a,b)[b&31];throw Error("nth after persistent!");};r.K=function(a,b,c){var d=0<=b;return(d?b<this.g:d)?a.F(a,b):c};r.I=function(){if(this.root.o)return this.g;throw Error("count after persistent!");};
function xc(a,b,c,d){if(a.root.o){if(function(){var b=0<=c;return b?c<a.g:b}()){if(ec(b)<=c)a.H[c&31]=d;else{var e=function h(b,e){var m=a.root.o===e.o?e:new dc(a.root.o,e.a.slice());if(0===b)m.a[c&31]=d;else{var p=c>>>b&31,q=h(b-5,m.a[p]);m.a[p]=q}return m}.call(null,a.shift,a.root);a.root=e}return b}if(c===a.g)return b.ta(b,d);throw Error([x("Index "),x(c),x(" out of bounds for TransientVector of length"),x(a.g)].join(""));}throw Error("assoc! after persistent!");}
r.oa=function(a,b,c){return xc(a,a,b,c)};r.ta=function(a,b){if(this.root.o){if(32>this.g-ec(a))this.H[this.g&31]=b;else{var c=new dc(this.root.o,this.H),d=Array(32);d[0]=b;this.H=d;if(this.g>>>5>1<<this.shift){var d=Array(32),e=this.shift+5;d[0]=this.root;d[1]=fc(this.root.o,this.shift,c);this.root=new dc(this.root.o,d);this.shift=e}else this.root=wc(a,this.shift,this.root,c)}this.g+=1;return a}throw Error("conj! after persistent!");};
r.ya=function(a){if(this.root.o){this.root.o=null;a=this.g-ec(a);var b=Array(a);xb(this.H,0,b,0,a);return new X(null,this.g,this.shift,this.root,b,null)}throw Error("persistent! called twice");};function yc(){this.q=0;this.h=2097152}yc.prototype.A=n(!1);var zc=new yc;function Ac(a,b){return yb(ub(b)?R(a)===R(b)?ac(bc,cc.b(function(a){return cb.b(nb.c(b,H(a),zc),H(M(a)))},a)):null:null)}
function Bc(a,b){var c,d,e,f=a.a,h=ca(b);if(h?h:"number"===typeof b)a:{for(var h=f.length,k=0;;){if(h<=k){f=-1;break a}if(b===f[k]){f=k;break a}k+=2}f=void 0}else if(null==b)a:{h=f.length;for(k=0;;){if(h<=k){f=-1;break a}if(null==f[k]){f=k;break a}k+=2}f=void 0}else a:{h=f.length;for(k=0;;){if(h<=k){f=-1;break a}if(cb.b(b,f[k])){f=k;break a}k+=2}f=void 0}return f}function Cc(a,b,c){this.a=a;this.j=b;this.za=c;this.q=0;this.h=32374990}r=Cc.prototype;r.D=function(a){return O(a)};
r.ha=function(){return this.j<this.a.length-2?new Cc(this.a,this.j+2,this.za):null};r.C=function(a,b){return P(b,a)};r.toString=function(){return F(this)};r.O=function(a,b){return U.b(b,a)};r.P=function(a,b,c){return U.c(b,c,a)};r.G=ba();r.I=function(){return(this.a.length-this.j)/2};r.R=function(){return qc([this.a[this.j],this.a[this.j+1]])};r.S=function(){return this.j<this.a.length-2?new Cc(this.a,this.j+2,this.za):L};r.A=function(a,b){return Q(a,b)};
r.Q=function(a,b){return new Cc(this.a,this.j,b)};r.N=g("za");function pa(a,b,c,d){this.n=a;this.g=b;this.a=c;this.l=d;this.q=4;this.h=16123663}r=pa.prototype;r.xa=function(){return new Dc({},this.a.length,this.a.slice())};r.D=function(a){var b=this.l;return null!=b?b:this.l=a=Ib(a)};r.U=function(a,b){return a.L(a,b,null)};r.L=function(a,b,c){a=Bc(a,b);return-1===a?c:this.a[a+1]};
r.ca=function(a,b,c){var d=Bc(a,b);if(-1===d){if(this.g<Ec){var d=a.a,e=d.length;a=Array(e+2);for(var f=0;;)if(f<e)a[f]=d[f],f+=1;else break;a[e]=b;a[e+1]=c;return new pa(this.n,this.g+1,a,null)}d=Ka;e=Ba;f=Fc;if(null!=f){var h;h=f?((h=f.q&4)?h:f.ob)?!0:!1:!1;h?(a=Cb.c(Va,Ua(f),a),a=Wa(a)):a=Cb.c(wa,f,a)}else a=Cb.c(jb,L,a);return d(e(a,b,c),this.n)}if(c===this.a[d+1])return a;b=this.a.slice();b[d+1]=c;return new pa(this.n,this.g,b,null)};
r.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.U(this,c);case 3:return this.L(this,c,d)}throw Error("Invalid arity: "+arguments.length);}}();r.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};r.C=function(a,b){return vb(b)?a.ca(a,z.b(b,0),z.b(b,1)):Cb.c(wa,a,b)};r.toString=function(){return F(this)};r.G=function(){return 0<=this.a.length-2?new Cc(this.a,0,null):null};r.I=g("g");r.A=function(a,b){return Ac(a,b)};
r.Q=function(a,b){return new pa(b,this.g,this.a,this.l)};r.N=g("n");var Gc=new pa(null,0,[],null),Ec=8;function Dc(a,b,c){this.pa=a;this.fa=b;this.a=c;this.q=56;this.h=258}r=Dc.prototype;r.oa=function(a,b,c){if(t(this.pa)){var d=Bc(a,b);if(-1===d){if(this.fa+2<=2*Ec)return this.fa+=2,this.a.push(b),this.a.push(c),a;a=Hc.b?Hc.b(this.fa,this.a):Hc.call(null,this.fa,this.a);return Xa(a,b,c)}c!==this.a[d+1]&&(this.a[d+1]=c);return a}throw Error("assoc! after persistent!");};
r.ta=function(a,b){if(t(this.pa)){var c;c=b?((c=b.h&2048)?c:b.bb)?!0:b.h?!1:v(Da,b):v(Da,b);if(c)return a.oa(a,V.e?V.e(b):V.call(null,b),W.e?W.e(b):W.call(null,b));c=G(b);for(var d=a;;){var e=H(c);if(t(e))c=M(c),d=d.oa(d,V.e?V.e(e):V.call(null,e),W.e?W.e(e):W.call(null,e));else return d}}else throw Error("conj! after persistent!");};r.ya=function(){if(t(this.pa))return this.pa=!1,new pa(null,Db((this.fa-this.fa%2)/2),this.a,null);throw Error("persistent! called twice");};
r.U=function(a,b){return a.L(a,b,null)};r.L=function(a,b,c){if(t(this.pa))return a=Bc(a,b),-1===a?c:this.a[a+1];throw Error("lookup after persistent!");};r.I=function(){if(t(this.pa))return Db((this.fa-this.fa%2)/2);throw Error("count after persistent!");};function Hc(a,b){for(var c=Ua(Fc),d=0;;)if(d<a)c=Xa(c,b[d],b[d+1]),d+=2;else return c}function Ic(){this.ba=!1}function Jc(a,b){return ca(a)?a===b:cb.b(a,b)}
var Kc=function(){function a(a,b,c,h,k){a=a.slice();a[b]=c;a[h]=k;return a}function b(a,b,c){a=a.slice();a[b]=c;return a}var c=null,c=function(c,e,f,h,k){switch(arguments.length){case 3:return b.call(this,c,e,f);case 5:return a.call(this,c,e,f,h,k)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.J=a;return c}(),Lc=function(){function a(a,b,c,h,k,l){a=a.qa(b);a.a[c]=h;a.a[k]=l;return a}function b(a,b,c,h){a=a.qa(b);a.a[c]=h;return a}var c=null,c=function(c,e,f,h,k,l){switch(arguments.length){case 4:return b.call(this,
c,e,f,h);case 6:return a.call(this,c,e,f,h,k,l)}throw Error("Invalid arity: "+arguments.length);};c.p=b;c.da=a;return c}();function Mc(a,b,c){this.o=a;this.v=b;this.a=c}r=Mc.prototype;
r.Y=function(a,b,c,d,e,f){var h=1<<(c>>>b&31),k=Eb(this.v&h-1);if(0===(this.v&h)){var l=Eb(this.v);if(2*l<this.a.length){a=this.qa(a);b=a.a;f.ba=!0;a:for(c=2*(l-k),f=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[f];l-=1;c-=1;f-=1}b[2*k]=d;b[2*k+1]=e;a.v|=h;return a}if(16<=l){k=Array(32);k[c>>>b&31]=Nc.Y(a,b+5,c,d,e,f);for(e=d=0;;)if(32>d)0!==(this.v>>>d&1)&&(k[d]=null!=this.a[e]?Nc.Y(a,b+5,S.e(this.a[e]),this.a[e],this.a[e+1],f):this.a[e+1],e+=2),d+=1;else break;return new Oc(a,l+1,k)}b=Array(2*
(l+4));xb(this.a,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;xb(this.a,2*k,b,2*(k+1),2*(l-k));f.ba=!0;a=this.qa(a);a.a=b;a.v|=h;return a}l=this.a[2*k];h=this.a[2*k+1];if(null==l)return l=h.Y(a,b+5,c,d,e,f),l===h?this:Lc.p(this,a,2*k+1,l);if(Jc(d,l))return e===h?this:Lc.p(this,a,2*k+1,e);f.ba=!0;return Lc.da(this,a,2*k,null,2*k+1,Pc.na?Pc.na(a,b+5,l,h,c,d,e):Pc.call(null,a,b+5,l,h,c,d,e))};r.va=function(){return Qc.e?Qc.e(this.a):Qc.call(null,this.a)};
r.qa=function(a){if(a===this.o)return this;var b=Eb(this.v),c=Array(0>b?4:2*(b+1));xb(this.a,0,c,0,2*b);return new Mc(a,this.v,c)};
r.X=function(a,b,c,d,e){var f=1<<(b>>>a&31),h=Eb(this.v&f-1);if(0===(this.v&f)){var k=Eb(this.v);if(16<=k){h=Array(32);h[b>>>a&31]=Nc.X(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.v>>>c&1)&&(h[c]=null!=this.a[d]?Nc.X(a+5,S.e(this.a[d]),this.a[d],this.a[d+1],e):this.a[d+1],d+=2),c+=1;else break;return new Oc(null,k+1,h)}a=Array(2*(k+1));xb(this.a,0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;xb(this.a,2*h,a,2*(h+1),2*(k-h));e.ba=!0;return new Mc(null,this.v|f,a)}k=this.a[2*h];f=this.a[2*h+1];if(null==k)return k=f.X(a+
5,b,c,d,e),k===f?this:new Mc(null,this.v,Kc.c(this.a,2*h+1,k));if(Jc(c,k))return d===f?this:new Mc(null,this.v,Kc.c(this.a,2*h+1,d));e.ba=!0;return new Mc(null,this.v,Kc.J(this.a,2*h,null,2*h+1,Pc.da?Pc.da(a+5,k,f,b,c,d):Pc.call(null,a+5,k,f,b,c,d)))};r.ma=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.v&e))return d;var f=Eb(this.v&e-1),e=this.a[2*f],f=this.a[2*f+1];return null==e?f.ma(a+5,b,c,d):Jc(c,e)?f:d};var Nc=new Mc(null,0,[]);function Oc(a,b,c){this.o=a;this.g=b;this.a=c}r=Oc.prototype;
r.Y=function(a,b,c,d,e,f){var h=c>>>b&31,k=this.a[h];if(null==k)return a=Lc.p(this,a,h,Nc.Y(a,b+5,c,d,e,f)),a.g+=1,a;b=k.Y(a,b+5,c,d,e,f);return b===k?this:Lc.p(this,a,h,b)};r.va=function(){return Rc.e?Rc.e(this.a):Rc.call(null,this.a)};r.qa=function(a){return a===this.o?this:new Oc(a,this.g,this.a.slice())};
r.X=function(a,b,c,d,e){var f=b>>>a&31,h=this.a[f];if(null==h)return new Oc(null,this.g+1,Kc.c(this.a,f,Nc.X(a+5,b,c,d,e)));a=h.X(a+5,b,c,d,e);return a===h?this:new Oc(null,this.g,Kc.c(this.a,f,a))};r.ma=function(a,b,c,d){var e=this.a[b>>>a&31];return null!=e?e.ma(a+5,b,c,d):d};function Sc(a,b,c){b*=2;for(var d=0;;)if(d<b){if(Jc(c,a[d]))return d;d+=2}else return-1}function Tc(a,b,c,d){this.o=a;this.ia=b;this.g=c;this.a=d}r=Tc.prototype;
r.Y=function(a,b,c,d,e,f){if(c===this.ia){b=Sc(this.a,this.g,d);if(-1===b){if(this.a.length>2*this.g)return a=Lc.da(this,a,2*this.g,d,2*this.g+1,e),f.ba=!0,a.g+=1,a;c=this.a.length;b=Array(c+2);xb(this.a,0,b,0,c);b[c]=d;b[c+1]=e;f.ba=!0;f=this.g+1;a===this.o?(this.a=b,this.g=f,a=this):a=new Tc(this.o,this.ia,f,b);return a}return this.a[b+1]===e?this:Lc.p(this,a,b+1,e)}return(new Mc(a,1<<(this.ia>>>b&31),[null,this,null,null])).Y(a,b,c,d,e,f)};
r.va=function(){return Qc.e?Qc.e(this.a):Qc.call(null,this.a)};r.qa=function(a){if(a===this.o)return this;var b=Array(2*(this.g+1));xb(this.a,0,b,0,2*this.g);return new Tc(a,this.ia,this.g,b)};r.X=function(a,b,c,d,e){return b===this.ia?(a=Sc(this.a,this.g,c),-1===a?(a=this.a.length,b=Array(a+2),xb(this.a,0,b,0,a),b[a]=c,b[a+1]=d,e.ba=!0,new Tc(null,this.ia,this.g+1,b)):cb.b(this.a[a],d)?this:new Tc(null,this.ia,this.g,Kc.c(this.a,a+1,d))):(new Mc(null,1<<(this.ia>>>a&31),[null,this])).X(a,b,c,d,e)};
r.ma=function(a,b,c,d){a=Sc(this.a,this.g,c);return 0>a?d:Jc(c,this.a[a])?this.a[a+1]:d};
var Pc=function(){function a(a,b,c,h,k,l,m){var p=S.e(c);if(p===k)return new Tc(null,p,2,[c,h,l,m]);var q=new Ic;return Nc.Y(a,b,p,c,h,q).Y(a,b,k,l,m,q)}function b(a,b,c,h,k,l){var m=S.e(b);if(m===h)return new Tc(null,m,2,[b,c,k,l]);var p=new Ic;return Nc.X(a,m,b,c,p).X(a,h,k,l,p)}var c=null,c=function(c,e,f,h,k,l,m){switch(arguments.length){case 6:return b.call(this,c,e,f,h,k,l);case 7:return a.call(this,c,e,f,h,k,l,m)}throw Error("Invalid arity: "+arguments.length);};c.da=b;c.na=a;return c}();
function Uc(a,b,c,d,e){this.n=a;this.Z=b;this.j=c;this.$=d;this.l=e;this.q=0;this.h=32374860}r=Uc.prototype;r.D=function(a){var b=this.l;return null!=b?b:this.l=a=O(a)};r.C=function(a,b){return P(b,a)};r.toString=function(){return F(this)};r.O=function(a,b){return U.b(b,a)};r.P=function(a,b,c){return U.c(b,c,a)};r.G=ba();r.R=function(){return null==this.$?qc([this.Z[this.j],this.Z[this.j+1]]):H(this.$)};
r.S=function(){return null==this.$?Qc.c?Qc.c(this.Z,this.j+2,null):Qc.call(null,this.Z,this.j+2,null):Qc.c?Qc.c(this.Z,this.j,M(this.$)):Qc.call(null,this.Z,this.j,M(this.$))};r.A=function(a,b){return Q(a,b)};r.Q=function(a,b){return new Uc(b,this.Z,this.j,this.$,this.l)};r.N=g("n");
var Qc=function(){function a(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new Uc(null,a,b,null,null);var h=a[b+1];if(t(h)&&(h=h.va(),t(h)))return new Uc(null,a,b+2,h,null);b+=2}else return null;else return new Uc(null,a,b,c,null)}function b(a){return c.c(a,0,null)}var c=null,c=function(c,e,f){switch(arguments.length){case 1:return b.call(this,c);case 3:return a.call(this,c,e,f)}throw Error("Invalid arity: "+arguments.length);};c.e=b;c.c=a;return c}();
function Vc(a,b,c,d,e){this.n=a;this.Z=b;this.j=c;this.$=d;this.l=e;this.q=0;this.h=32374860}r=Vc.prototype;r.D=function(a){var b=this.l;return null!=b?b:this.l=a=O(a)};r.C=function(a,b){return P(b,a)};r.toString=function(){return F(this)};r.O=function(a,b){return U.b(b,a)};r.P=function(a,b,c){return U.c(b,c,a)};r.G=ba();r.R=function(){return H(this.$)};r.S=function(){return Rc.p?Rc.p(null,this.Z,this.j,M(this.$)):Rc.call(null,null,this.Z,this.j,M(this.$))};r.A=function(a,b){return Q(a,b)};
r.Q=function(a,b){return new Vc(b,this.Z,this.j,this.$,this.l)};r.N=g("n");var Rc=function(){function a(a,b,c,h){if(null==h)for(h=b.length;;)if(c<h){var k=b[c];if(t(k)&&(k=k.va(),t(k)))return new Vc(a,b,c+1,k,null);c+=1}else return null;else return new Vc(a,b,c,h,null)}function b(a){return c.p(null,a,0,null)}var c=null,c=function(c,e,f,h){switch(arguments.length){case 1:return b.call(this,c);case 4:return a.call(this,c,e,f,h)}throw Error("Invalid arity: "+arguments.length);};c.e=b;c.p=a;return c}();
function Wc(a,b,c,d,e,f){this.n=a;this.g=b;this.root=c;this.T=d;this.V=e;this.l=f;this.q=4;this.h=16123663}r=Wc.prototype;r.xa=function(){return new Xc({},this.root,this.g,this.T,this.V)};r.D=function(a){var b=this.l;return null!=b?b:this.l=a=Ib(a)};r.U=function(a,b){return a.L(a,b,null)};r.L=function(a,b,c){return null==b?this.T?this.V:c:null==this.root?c:this.root.ma(0,S.e(b),b,c)};
r.ca=function(a,b,c){if(null==b){var d=this.T;return(d?c===this.V:d)?a:new Wc(this.n,this.T?this.g:this.g+1,this.root,!0,c,null)}d=new Ic;c=(null==this.root?Nc:this.root).X(0,S.e(b),b,c,d);return c===this.root?a:new Wc(this.n,d.ba?this.g+1:this.g,c,this.T,this.V,null)};r.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.U(this,c);case 3:return this.L(this,c,d)}throw Error("Invalid arity: "+arguments.length);}}();
r.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};r.C=function(a,b){return vb(b)?a.ca(a,z.b(b,0),z.b(b,1)):Cb.c(wa,a,b)};r.toString=function(){return F(this)};r.G=function(){if(0<this.g){var a=null!=this.root?this.root.va():null;return this.T?P(qc([null,this.V]),a):a}return null};r.I=g("g");r.A=function(a,b){return Ac(a,b)};r.Q=function(a,b){return new Wc(b,this.g,this.root,this.T,this.V,this.l)};r.N=g("n");var Fc=new Wc(null,0,null,!1,null,0);
function Xc(a,b,c,d,e){this.o=a;this.root=b;this.count=c;this.T=d;this.V=e;this.q=56;this.h=258}r=Xc.prototype;r.oa=function(a,b,c){return Yc(a,b,c)};r.ta=function(a,b){var c;a:{if(a.o){c=b?((c=b.h&2048)?c:b.bb)?!0:b.h?!1:v(Da,b):v(Da,b);if(c){c=Yc(a,V.e?V.e(b):V.call(null,b),W.e?W.e(b):W.call(null,b));break a}c=G(b);for(var d=a;;){var e=H(c);if(t(e))c=M(c),d=Yc(d,V.e?V.e(e):V.call(null,e),W.e?W.e(e):W.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");c=void 0}return c};
r.ya=function(a){if(a.o)a.o=null,a=new Wc(null,a.count,a.root,a.T,a.V,null);else throw Error("persistent! called twice");return a};r.U=function(a,b){return null==b?this.T?this.V:null:null==this.root?null:this.root.ma(0,S.e(b),b)};r.L=function(a,b,c){return null==b?this.T?this.V:c:null==this.root?c:this.root.ma(0,S.e(b),b,c)};r.I=function(){if(this.o)return this.count;throw Error("count after persistent!");};
function Yc(a,b,c){if(a.o){if(null==b)a.V!==c&&(a.V=c),a.T||(a.count+=1,a.T=!0);else{var d=new Ic;b=(null==a.root?Nc:a.root).Y(a.o,0,S.e(b),b,c,d);b!==a.root&&(a.root=b);d.ba&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}
var ob=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){for(var b=G(a),e=Ua(Fc);;)if(b){a=M(M(b));var f=H(b),b=H(M(b)),e=Xa(e,f,b),b=a}else return Wa(e)}a.r=0;a.m=function(a){a=G(a);return b(a)};a.k=b;return a}();function V(a){return Ea(a)}function W(a){return Fa(a)}
function Zc(a){var b;b=a?((b=a.q&4096)?b:a.eb)?!0:!1:!1;if(b)return a.name;if(qa(a))return a;if(zb(a))return b=a.lastIndexOf("/",a.length-2),0>b?Gb.b(a,2):Gb.b(a,b+1);throw Error([x("Doesn't support name: "),x(a)].join(""));}function $c(a){var b;b=a?((b=a.q&4096)?b:a.eb)?!0:!1:!1;if(b)return a.wb;if(zb(a))return b=a.lastIndexOf("/",a.length-2),-1<b?Gb.c(a,2,b):null;throw Error([x("Doesn't support namespace: "),x(a)].join(""));}
function Z(a,b,c,d,e,f,h){E(a,c);G(h)&&(b.c?b.c(H(h),a,f):b.call(null,H(h),a,f));c=G(M(h));h=null;for(var k=0,l=0;;)if(l<k){var m=h.F(h,l);E(a,d);b.c?b.c(m,a,f):b.call(null,m,a,f);l+=1}else if(c=G(c))h=c,wb(h)?(c=Za(h),l=$a(h),h=c,k=R(c),c=l):(c=H(h),E(a,d),b.c?b.c(c,a,f):b.call(null,c,a,f),c=M(h),h=null,k=0),l=0;else break;return E(a,e)}
var ad=function(){function a(a,d){var e=null;1<arguments.length&&(e=N(Array.prototype.slice.call(arguments,1),0));return b.call(this,a,e)}function b(a,b){for(var e=G(b),f=null,h=0,k=0;;)if(k<h){var l=f.F(f,k);E(a,l);k+=1}else if(e=G(e))f=e,wb(f)?(e=Za(f),h=$a(f),f=e,l=R(e),e=h,h=l):(l=H(f),E(a,l),e=M(f),f=null,h=0),k=0;else return null}a.r=1;a.m=function(a){var d=H(a);a=J(a);return b(d,a)};a.k=b;return a}();function bd(a){ia.e?ia.e(a):ia.call(null,a);return null}
var cd={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function dd(a){return[x('"'),x(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return cd[a]})),x('"')].join("")}
var $=function ed(b,c,d){if(null==b)return E(c,"nil");if(void 0===b)return E(c,"#\x3cundefined\x3e");t(function(){var c=nb.b(d,"\ufdd0:meta");return t(c)?(c=b?((c=b.h&131072)?c:b.cb)?!0:b.h?!1:v(Ia,b):v(Ia,b),t(c)?rb(b):c):c}())&&(E(c,"^"),ed(rb(b),c,d),E(c," "));if(null==b)return E(c,"nil");if(b.ib)return b.ub(c);if(function(){var c;c=b?((c=b.h&2147483648)?c:b.M)?!0:!1:!1;return c}())return b.B(b,c,d);if(function(){var c=sa(b)===Boolean;return c?c:"number"===typeof b}())return E(c,""+x(b));if(b instanceof
Array)return Z(c,ed,"#\x3cArray [",", ","]\x3e",d,b);if(ca(b)){if(zb(b)){E(c,":");var e=$c(b);t(e)&&ad.k(c,N([""+x(e),"/"],0));return E(c,Zc(b))}return t((new Mb("\ufdd0:readably")).call(null,d))?E(c,dd(b)):E(c,b)}return qb(b)?ad.k(c,N(["#\x3c",""+x(b),"\x3e"],0)):b instanceof Date?(e=function(b,c){for(var d=""+x(b);;)if(R(d)<c)d=[x("0"),x(d)].join("");else return d},ad.k(c,N(['#inst "',""+x(b.getUTCFullYear()),"-",e(b.getUTCMonth()+1,2),"-",e(b.getUTCDate(),2),"T",e(b.getUTCHours(),2),":",e(b.getUTCMinutes(),
2),":",e(b.getUTCSeconds(),2),".",e(b.getUTCMilliseconds(),3),"-",'00:00"'],0))):t(b instanceof RegExp)?ad.k(c,N(['#"',b.source,'"'],0)):function(){var c;c=b?((c=b.h&2147483648)?c:b.M)?!0:b.h?!1:v(Sa,b):v(Sa,b);return c}()?Ta(b,c,d):ad.k(c,N(["#\x3c",""+x(b),"\x3e"],0))},fd=function(){function a(a){var d=null;0<arguments.length&&(d=N(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b=pb.c(oa(),"\ufdd0:readably",!1),e=bd,f=null==a;f||(f=G(a),f=t(f)?!1:!0);if(f)b=
"";else{var f=x,h=new ha,k=new ab(h);a:{$(H(a),k,b);a=G(M(a));for(var l=null,m=0,p=0;;)if(p<m){var q=l.F(l,p);E(k," ");$(q,k,b);p+=1}else if(a=G(a))l=a,wb(l)?(a=Za(l),m=$a(l),l=a,q=R(a),a=m,m=q):(q=H(l),E(k," "),$(q,k,b),a=M(l),l=null,m=0),p=0;else break a}Ra(k);b=""+f(h)}e(b);e=oa();bd("\n");return nb.b(e,"\ufdd0:flush-on-newline"),null}a.r=0;a.m=function(a){a=G(a);return b(a)};a.k=b;return a}();bb.prototype.M=!0;bb.prototype.B=function(a,b,c){return Z(b,$,"("," ",")",c,a)};tc.prototype.M=!0;
tc.prototype.B=function(a,b,c){return Z(b,$,"["," ","]",c,a)};Sb.prototype.M=!0;Sb.prototype.B=function(a,b,c){return Z(b,$,"("," ",")",c,a)};pa.prototype.M=!0;pa.prototype.B=function(a,b,c){return Z(b,function(a){return Z(b,$,""," ","",c,a)},"{",", ","}",c,a)};Ob.prototype.M=!0;Ob.prototype.B=function(a,b,c){return Z(b,$,"("," ",")",c,a)};Uc.prototype.M=!0;Uc.prototype.B=function(a,b,c){return Z(b,$,"("," ",")",c,a)};rc.prototype.M=!0;rc.prototype.B=function(a,b,c){return Z(b,$,"("," ",")",c,a)};
Wc.prototype.M=!0;Wc.prototype.B=function(a,b,c){return Z(b,function(a){return Z(b,$,""," ","",c,a)},"{",", ","}",c,a)};X.prototype.M=!0;X.prototype.B=function(a,b,c){return Z(b,$,"["," ","]",c,a)};Jb.prototype.M=!0;Jb.prototype.B=function(a,b,c){return Z(b,$,"("," ",")",c,a)};Cc.prototype.M=!0;Cc.prototype.B=function(a,b,c){return Z(b,$,"("," ",")",c,a)};Kb.prototype.M=!0;Kb.prototype.B=function(a,b){return E(b,"()")};Lb.prototype.M=!0;Lb.prototype.B=function(a,b,c){return Z(b,$,"("," ",")",c,a)};
Vc.prototype.M=!0;Vc.prototype.B=function(a,b,c){return Z(b,$,"("," ",")",c,a)};X.prototype.Ua=!0;X.prototype.Va=function(a,b){return Bb.b(a,b)};tc.prototype.Ua=!0;tc.prototype.Va=function(a,b){return Bb.b(a,b)};function gd(a,b,c,d){this.state=a;this.n=b;this.xb=c;this.yb=d;this.h=2153938944;this.q=2}gd.prototype.D=function(a){return a[da]||(a[da]=++ea)};gd.prototype.B=function(a,b,c){E(b,"#\x3cAtom: ");$(this.state,b,c);return E(b,"\x3e")};gd.prototype.N=g("n");
gd.prototype.A=function(a,b){return a===b};(function(){function a(a){return new gd(a,null,null,null)}var b=null,c=function(){function a(c,d){var k=null;1<arguments.length&&(k=N(Array.prototype.slice.call(arguments,1),0));return b.call(this,c,k)}function b(a,c){var d;d=null==c?!1:c?((d=c.h&64)?d:c.sa)?!0:c.h?!1:v(ya,c):v(ya,c);var e=d?$b.b(ob,c):c;d=nb.b(e,"\ufdd0:validator");e=nb.b(e,"\ufdd0:meta");return new gd(a,e,d,null)}a.r=1;a.m=function(a){var c=H(a);a=J(a);return b(c,a)};a.k=b;return a}(),b=function(b,e){switch(arguments.length){case 1:return a.call(this,
b);default:return c.k(b,N(arguments,1))}throw Error("Invalid arity: "+arguments.length);};b.r=1;b.m=c.m;b.e=a;b.k=c.k;return b})().e(Gc);ra=function(){var a=require("./my_api");return fd.k(N([a.more3],0))};var hd=require,id=process,bd=(hd.e?hd.e("util"):hd.call(null,"util")).print;$b.b(ra,function(a,b){return new Ob(null,!1,function(){var c;a:{c=a;for(var d=b;;){var d=G(d),e=0<c;if(t(e?d:e))c-=1,d=J(d);else{c=d;break a}}c=void 0}return c},null)}(2,id.lb));